// ChunkEar 语义模块语料库（6级，从Python corpus.py转换）
const CORPUS = [
  {
    id: 0,
    name: '极简根基',
    color: '#27ae60',
    modules: [
      ['Hello.', '你好。'],
      ['Hi.', '嗨。'],
      ['Bye.', '再见。'],
      ['Okay.', '好的。/行。'],
      ['Yes.', '是的。'],
      ['No.', '不。'],
      ['Thanks.', '谢谢。'],
      ['Sorry.', '对不起。'],
      ['Please.', '请。'],
      ['Sure.', '当然。/没问题。'],
      ['Great.', '太好了。'],
      ['Right.', '对。/没错。'],
      ['Good.', '好。/不错。'],
      ['Fine.', '挺好的。/没事。'],
      ['Maybe.', '也许吧。'],
      ['Wait.', '等等。'],
      ['Really?', '真的吗？'],
      ['Exactly.', '正是。'],
      ['See?', '看到了吗？/明白吗？'],
      ['Thank you.', '谢谢你。'],
      ['Come on.', '快点。/加油。/别这样。'],
      ['Go on.', '继续。'],
      ['Of course.', '当然。'],
      ['All right.', '好吧。/行。/没事的。'],
      ['No problem.', '没问题。'],
      ["That's right.", '没错。'],
      ["That's fine.", '没事。/那也行。'],
      ['For sure.', '肯定的。'],
      ['Come here.', '过来。'],
      ['Look out!', '小心！'],
      ['Watch out!', '当心！'],
      ['Hurry up.', '快点。'],
      ['Calm down.', '冷静点。'],
      ['Sit down.', '坐下。'],
      ['Stand up.', '站起来。'],
      ['I see.', '我明白了。'],
      ['I know.', '我知道。'],
      ['Not yet.', '还没。'],
      ['So far.', '到目前为止。'],
      ['Too bad.', '太可惜了。/糟糕。'],
      ['Never mind.', '没关系。/算了。'],
      ['Good luck.', '祝你好运。'],
      ['Take care.', '保重。'],
      ['Well done.', '做得好。'],
      ['Me too.', '我也是。'],
      ['Same here.', '我也一样。'],
      ['No way!', '不可能！/没门！'],
      ['Absolutely.', '绝对地。/完全同意。'],
      ['Come on in.', '进来吧。'],
      ['Go ahead.', '请便。/继续吧。'],
    ]
  },
  {
    id: 1,
    name: '日常问候',
    color: '#2980b9',
    modules: [
      ['How are you?', '你好吗？'],
      ["How's it going?", '怎么样？/近来如何？'],
      ["What's up?", '咋样？/什么事？'],
      ["How's everything?", '一切可好？'],
      ['Pretty good.', '挺好的。'],
      ['Not too bad.', '还不赖。'],
      ['Could be better.', '一般般吧。'],
      ['Nice to meet you.', '很高兴认识你。'],
      ['Long time no see.', '好久不见。'],
      ["What's your name?", '你叫什么名字？'],
      ['My name is...', '我叫……'],
      ['Where are you from?', '你从哪里来？'],
      ["I'm from...", '我来自……'],
      ['What do you do?', '你是做什么的？'],
      ["I'm a student.", '我是学生。'],
      ['Nice talking to you.', '跟你聊得很愉快。'],
      ['See you later.', '回头见。'],
      ['See you tomorrow.', '明天见。'],
      ['Talk to you later.', '晚点再聊。'],
      ['Have a nice day.', '祝你过得愉快。'],
      ['Take it easy.', '别紧张。/悠着点。'],
      ['Catch you later.', '回头见。'],
      ['I gotta go.', '我得走了。'],
      ["I'm sorry.", '对不起。/我很遗憾。'],
      ['No worries.', '别担心。/没关系。'],
      ["That's okay.", '没事。'],
      ["Don't worry about it.", '别在意。'],
      ['Excuse me.', '打扰一下。/劳驾。'],
      ['Pardon me.', '抱歉。/请再说一遍？'],
      ['I beg your pardon?', '您说什么？'],
      ['Could you repeat that?', '你能再说一遍吗？'],
      ['Say that again?', '再说一遍？'],
      ['What did you say?', '你说什么？'],
      ["I didn't catch that.", '我没听清。'],
      ['Could you speak slower?', '能说慢点吗？'],
      ['Like this?', '像这样吗？'],
      ['For example?', '举个例子？'],
      ['What for?', '为什么？/干嘛用？'],
      ['How come?', '怎么会这样？'],
    ]
  },
  {
    id: 2,
    name: '生活常用',
    color: '#8e44ad',
    modules: [
      ["I don't know.", '我不知道。'],
      ["I don't understand.", '我不明白。'],
      ["I don't think so.", '我不这么认为。'],
      ['I think so.', '我觉得是的。'],
      ['I hope so.', '我希望如此。'],
      ['I guess so.', '我猜是吧。'],
      ["I'm not sure.", '我不确定。'],
      ['I have no idea.', '我完全不知道。'],
      ['That makes sense.', '有道理。'],
      ["That doesn't make sense.", '没道理。'],
      ['What do you mean?', '你什么意思？'],
      ["What's the matter?", '怎么了？'],
      ["What's wrong?", '出什么事了？'],
      ['What happened?', '发生什么了？'],
      ["What's going on?", '怎么回事？'],
      ['What should I do?', '我该怎么办？'],
      ['How does it work?', '这怎么用？'],
      ['How long does it take?', '要花多长时间？'],
      ['How much is it?', '多少钱？'],
      ['Is that okay?', '那样行吗？'],
      ['Are you ready?', '准备好了吗？'],
      ['Are you sure?', '你确定吗？'],
      ['Are you kidding?', '你开玩笑吧？'],
      ["You're welcome.", '不客气。'],
      ['My pleasure.', '我的荣幸。'],
      ['After you.', '您先请。'],
      ['Help yourself.', '请自便。/随便吃。'],
      ['Let me see.', '让我看看。/我想想。'],
      ['Let me check.', '让我查一下。'],
      ['Let me think.', '让我想想。'],
      ["Let's go.", '走吧。'],
      ["Let's do it.", '来吧。/开始干吧。'],
      ["It's up to you.", '你来决定。'],
      ["It doesn't matter.", '没关系。/无所谓。'],
      ['It depends.', '看情况。'],
      ["It's worth a try.", '值得一试。'],
      ['Here you are.', '给你。'],
      ['There you go.', '这就对了。/给你。'],
      ['Here we go.', '开始吧。/走了。'],
      ['One moment please.', '请稍等。'],
      ['Just a second.', '等一下。'],
      ['Hold on a second.', '稍等一下。'],
      ["I'll be right back.", '我马上回来。'],
      ["I'm on my way.", '我在路上了。'],
      ["That's a good idea.", '好主意。'],
      ['Sounds good.', '听起来不错。'],
      ['Fair enough.', '说得通。/行吧。'],
      ['Better late than never.', '迟做总比不做好。'],
      ['Take your time.', '慢慢来。/别着急。'],
      ['Time is up.', '时间到了。'],
      ["I'm busy right now.", '我现在很忙。'],
      ['Not a big deal.', '不是什么大事。'],
    ]
  },
  {
    id: 3,
    name: '表达观点',
    color: '#e67e22',
    modules: [
      ['In my opinion,', '在我看来，'],
      ['To be honest,', '老实说，'],
      ['To be fair,', '公平地说，'],
      ['As far as I know,', '据我所知，'],
      ['From my point of view,', '从我的角度看，'],
      ['The thing is,', '问题是，/事情是这样的，'],
      ['The point is,', '关键是，'],
      ['The truth is,', '事实是，'],
      ['The problem is,', '问题在于，'],
      ['As a matter of fact,', '事实上，'],
      ['At the same time,', '同时，/不过话又说回来，'],
      ['On the other hand,', '另一方面，'],
      ['On the contrary,', '恰恰相反，'],
      ['By the way,', '顺便说一下，'],
      ['In other words,', '换句话说，'],
      ['That is to say,', '也就是说，'],
      ['First of all,', '首先，'],
      ['Last but not least,', '最后但同样重要，'],
      ["What's more,", '而且，'],
      ['In addition,', '除此之外，'],
      ['Speaking of which,', '说到这个，'],
      ['That reminds me,', '那倒提醒了我，'],
      ['If you ask me,', '要我说的话，'],
      ['If I were you,', '如果我是你，'],
      ['I would say,', '我会说，'],
      ['I guess,', '我猜，'],
      ['I bet,', '我敢打赌，'],
      ["I'd rather,", '我宁愿，'],
      ["I'd like to,", '我想（做某事），'],
      ["I'm going to,", '我打算，/我要去，'],
      ["I'm supposed to,", '我应该，/按理要，'],
      ['I have to,', '我必须，'],
      ['I need to,', '我需要，'],
      ["I'm trying to,", '我正在试着，'],
      ["I'm afraid that,", '恐怕，'],
      ["I'm worried about,", '我担心，'],
      ["I'm looking for,", '我在找，'],
      ["I'm looking forward to,", '我期待着，'],
      ["I can't stand,", '我受不了，'],
      ["I can't help,", '我忍不住，'],
      ["I don't care,", '我不在乎，'],
      ['What I mean is,', '我的意思是，'],
      ['What I\'m trying to say is,', '我想说的是，'],
      ['Let me put it this way,', '我这么说吧，'],
      ['More or less,', '或多或少。/基本上，'],
    ]
  },
  {
    id: 4,
    name: '高级表达',
    color: '#c0392b',
    modules: [
      ['When it comes to,', '说到……/在……方面，'],
      ['In terms of,', '就……而言，'],
      ['Regardless of,', '不管……/无论……，'],
      ['In spite of that,', '尽管如此，'],
      ['As long as,', '只要……，'],
      ['Now that,', '既然……，'],
      ['No matter what,', '不管怎样，'],
      ['As a result,', '因此，/结果，'],
      ['In the end,', '最终/到头来，'],
      ['At the end of the day,', '归根结底，'],
      ['In the long run,', '从长远来看，'],
      ['In the meantime,', '与此同时，'],
      ['All of a sudden,', '突然，'],
      ['Sooner or later,', '迟早，'],
      ['Believe it or not,', '信不信由你，'],
      ['Guess what?', '你猜怎么着？'],
      ['You know what?', '你知道吗？'],
      ['Long story short,', '长话短说，'],
      ['In a nutshell,', '简而言之，'],
      ['As usual,', '像往常一样，'],
      ['Needless to say,', '不用说，'],
      ['It goes without saying,', '不言而喻，'],
      ["It's no wonder that,", '难怪……，'],
      ['No wonder,', '难怪，'],
      ['What if,', '要是……呢？'],
      ['Even if,', '即使/就算，'],
      ['It seems like,', '看起来好像，'],
      ['It looks like,', '看起来像是，'],
      ['It sounds like,', '听起来像是，'],
      ['It turns out that,', '结果发现，'],
      ['It occurred to me that,', '我突然想到，'],
      ["There's no way,", '不可能，'],
      ['There must be,', '一定有，'],
      ['The more I think about it,', '我越想越觉得，'],
    ]
  },
  {
    id: 5,
    name: '精通自动化',
    color: '#d35400',
    modules: [
      ['Having said that,', '话虽如此，'],
      ['That being said,', '话虽这么说，'],
      ['All things considered,', '综合考虑来看，'],
      ['One way or another,', '无论如何，'],
      ['Either way,', '不管怎样，'],
      ['For what it\'s worth,', '不管有没有用，'],
      ['Off the top of my head,', '凭直觉，'],
      ['On second thought,', '转念一想，'],
      ['Come to think of it,', '仔细一想，'],
      ["I've been meaning to,", '我一直想，'],
      ['I was wondering if,', '我想请问是否，'],
      ["It's safe to say that,", '可以这么说，'],
      ["It's fair to say that,", '公平地说，'],
      ["There is no doubt that,", '毫无疑问，'],
      ['Without a doubt,', '毫无疑问，'],
      ['By all means,', '当然可以，'],
      ['By no means,', '绝不，'],
      ['For the most part,', '大部分情况下，'],
      ['By and large,', '总的来说，'],
      ['On the whole,', '总体上来看，'],
      ['In general,', '一般来说，'],
      ['In particular,', '尤其是，'],
      ['First and foremost,', '首先最重要的是，'],
      ['In any case,', '无论如何，'],
      ['In that case,', '那样的话，'],
      ['Otherwise,', '否则，'],
      ['So to speak,', '可以这么说，'],
      ['So what?', '那又怎样？'],
      ["What's the point?", '有什么意义呢？'],
      ['You never know.', '谁知道呢。'],
      ["You're telling me.", '可不是嘛。'],
      ['Tell me about it.', '可不是嘛。'],
      ['I hear you.', '我明白你的意思。'],
      ["You've got a point.", '你说得有道理。'],
      ['Fair point.', '有道理。'],
      ['Point taken.', '说得对。'],
    ]
  }
];
